packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^22
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vercel/analytics': ^1.5.0
  next: ^15.5.6
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@firebase/util'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - protobufjs
  - sharp
  - unrs-resolver
